import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AppSidebar } from "@/components/app-sidebar"

import { cookies } from "next/headers";

import {
  SidebarInset,
  SidebarProvider, 
} from "@/components/ui/sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "PolyLearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const isLoggedIn = cookies()).get("auth_token");
  // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  
  return (
    <html lang="en">
      <body
      >{

      }
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          
          {children}
          
        </SidebarInset>
      </SidebarProvider>
      </body>
    </html>
  );
}
